- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: create
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: test
    url: https://18.234.160.149:8080
    user: admin
    password: "{{jenkins_password}}"

  loop:
    - frontend
    - catalogue
    - cart